Initial implementation of import-inputs command
GoogleCloudPlatform/hpc-toolkit pull request #1228
Opened 2023-04-26 21:33 UTC by tpdownes

Initial implementation of import-inputs

- read metadata to identify intergroup outputs necessary for target
  deployment group
- collect output values from prior groups and combine into a single file
  in the target deployment group directory

Does not yet support the evaluation of module settings that is necessary for writing to Packer deployment groups. This is anticipated in a follow-up PR now that #1205 has been merged.

Suggest testing with `igc_tf_test.yaml` under tools directory. With this approach one would run:

```shell
terraform -chdir=igc-tf-test/zero init
terraform -chdir=igc-tf-test/zero validate
terraform -chdir=igc-tf-test/zero apply
ghpc export-outputs igc-tf-test/zero

ghpc import-inputs igc-tf-test/one
terraform -chdir=igc-tf-test/one init
terraform -chdir=igc-tf-test/one validate
terraform -chdir=igc-tf-test/one apply
```

2023-04-26 21:40 UTC, tpdownes commented on pkg/shell/terraform.go
> +			return fmt.Errorf("could not load file %s; consider running \"ghpc export-outputs %s/%s\".\n%v", filepath, deploymentRoot, group, err)
@nick-stroud I realize this is probably a good candidate for `TfError`. Will update after review.

2023-04-27 23:56 UTC, nick-stroud requested changes

2023-05-01 15:41 UTC, tpdownes commented on pkg/shell/terraform.go
> +			return fmt.Errorf("could not load file %s; consider running \"ghpc export-outputs %s/%s\".\n%v", filepath, deploymentRoot, group, err)
The replacement on HEAD will read:

```shell
2023/05/01 10:39:17 collecting outputs for group one from group zero
Error: consider running "ghpc export-outputs igc-tf-test/zero" (detailed error below)
The configuration file "igc-tf-test/.ghpc/zero_outputs.tfvars" could not be read.
```

2023-05-01 16:22 UTC, tpdownes commented on pkg/shell/terraform.go
> +	allAttributes := make(map[string]cty.Value)
Similar suggestions implemented.

2023-05-01 16:23 UTC, tpdownes commented on pkg/shell/common.go
> +func getOutputsFromEarlierGroups(thisGroup string, metadataFile string) (map[string][]string, error) {
Replaced with `getIntergroupOutputNamesByGroup`

2023-05-01 16:24 UTC, tpdownes commented on pkg/shell/terraform.go
> +	if _, err = GetDeploymentKinds(metadataFile, deploymentRoot); err != nil {
- function comment for `GetDeploymentKinds` improved
- anticipated import noted as TODO next to where it is called

2023-05-01 16:24 UTC, tpdownes commented on pkg/shell/terraform.go
> +func ImportInputs(workingDir, metadataFile string, artifactsDir string) error {
Done

2023-05-01 16:25 UTC, tpdownes commented on pkg/shell/terraform.go
> +func ImportInputs(workingDir, metadataFile string, artifactsDir string) error {
Resolved by adding type to all there. An edge case to how `golint` enforces function signatures.

2023-05-01 16:46 UTC, nick-stroud approved these changes

2023-05-01 16:56 UTC, merged