Add custom unmarshaler for `Module.Use`, allow "single use"
GoogleCloudPlatform/hpc-toolkit pull request #1473
Opened 2023-06-17 06:31 UTC by mr0re1

* Allow single module use;
* Improve unmarshalling error message;
* Move YAML-related code `pkg/config` into `yaml*.go`.

**NOTE to reviewer**:
Most of the changed lines a just moved.
The new code is in following functions:

* `(ms *ModuleIDs) UnmarshalYAML`;
* `TestModuleKindUnmarshalYAML`;
* `TestModuleIDsUnmarshalYAML`.

2023-06-20 18:19 UTC, tpdownes requested changes
1. Please update modules/README.md explicitly showing that `use` can accept a single string identifying a module _or_ a YAML list of string module IDs.

2. Update the error message shown below when a user naively adds a comma:

```text
invalid module reference: network1,homefs
```

Let's pick something more like:

`the use keyword accepts a single module ID or a YAML list of module IDs (goo.gle/hpc-toolkit-use): FULL_ERROR_MESSAGE_FROM_func_Module`

I can create the link and point it to the documentation in (1)

2023-06-21 22:29 UTC, mr0re1 commented
Removed support for "scalar" use. Can be added in the future with small effort.

2023-06-22 02:21 UTC, tpdownes approved these changes
Please do the following and merge:

- Fix the comment noted in the review
- Change the description of the PR
- Make sure any merge commit is accurate (might be derived from description)

2023-06-22 02:21 UTC, tpdownes commented on pkg/config/yaml.go
> +// UnmarshalYAML is a custom unmarshaler for Module.Use, that allows both single and list of ModuleID
update this comment

2023-06-22 17:56 UTC, merged