Allow to specify `vm-instance.placement_policy.max_distance`
GoogleCloudPlatform/hpc-toolkit pull request #1567
Opened 2023-07-11 20:54 UTC by mr0re1

* Switch to `google-beta` provider;
* Workaround lack of `optional` in TF 1.2, change type to `any`;
* Add validation of for "being a map/object", "only valid keys are usde".

2023-07-11 21:08 UTC, nick-stroud requested changes

2023-07-11 21:08 UTC, nick-stroud commented on modules/compute/vm-instance/README.md
I believe you need to update the required version of the beta provider in versions.tf. It is currently set to 4.12 which is very old and does not include the max_distance api.

2023-07-11 23:41 UTC, mr0re1 commented on modules/compute/vm-instance/README.md
IIUC it has to be done as a separate PR.

2023-07-12 14:14 UTC, nick-stroud commented on modules/compute/vm-instance/README.md
I don't think so, I am talking about this line: https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/a952bb7bec8ee89af38dab73d97556afd8765212/modules/compute/vm-instance/versions.tf#L26.

2023-07-12 16:29 UTC, tpdownes requested changes
I believe the changes requested make sense:

- bump minimum provider for this module
- improve error message guidance
- improve validation of field with single appropriate value

I am not sufficiently aware of resource policies (or roadmap) to know whether we should extend the validation logic to address known bad combinations:

```
Error: Error creating ResourcePolicy: googleapi: Error 400: Invalid value for field 'resource.groupPlacementPolicy': '{  "vmCount": 2,  "availabilityDomainCount": 2,  "collocation": "COLLOCATED",  "maxDistance": 2}'. A Spread GroupPlacementPolicy should not have vm count set, invalid
```

For now, I would err on the side of letting the API errors bubble up rather than over-constraining the user. It is easier to add validation logic than to take away.

2023-07-12 17:26 UTC, nick-stroud commented on modules/compute/vm-instance/variables.tf
> +  }
I would exclude validation for collocation. I can confirm it is validated by the terraform resource. Indicating type is still a good idea.

2023-07-12 18:41 UTC, mr0re1 commented on modules/compute/vm-instance/README.md
Thank you for clarification, completely missed it!

2023-07-12 18:59 UTC, tpdownes approved these changes

2023-07-12 19:33 UTC, merged