Forces VMs to be replaced when placement policy is destroyed
GoogleCloudPlatform/hpc-toolkit pull request #1849
Opened 2023-10-18 05:00 UTC by nick-stroud

Tested: 
- Deploy the VMs defined below
- Edit `max_distance` from 1 -> 2
- before change observe failure, cannot delete placement as it is used by VM
- after change it works

Note: If one does not turn `auto_delete_boot_disk: false` you will still get an error on second apply as it will not find disk. This can be worked around by doing another apply. This disk issue is a known pain point that is unrelated to the placement policy error.

```
  - id: workstation
    source: ./modules/compute/vm-instance
    use: [network1]
    settings:
      name_prefix: nstest
      machine_type: c2-standard-4
      auto_delete_boot_disk: false
      placement_policy:
        collocation: "COLLOCATED"
        max_distance: 1
      instance_count: 2
```

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2023-10-19 16:25 UTC, tpdownes requested changes
I trust that this works but I think `google_compute_resource_policy.placement_policy` might be a list/array all by itself and replace_triggered_by takes a list. So I think the solution might be a bit fragile. Can you wrap the array with `flatten` and repeat test?

2023-10-19 18:07 UTC, nick-stroud commented
> Can you wrap the array with `flatten` and repeat test?

I tried but I get `Unexpected expression found in replace_triggered_by.` or `A static list expression is required.`.

From poking around online it looks like `replace_triggered_by` requires "static references" and cannot accept an expression. 

Additionally the documentation for `replace_triggered_by` states:
> If the reference is to a resource with multiple instances, a plan to update or replace any instance will trigger replacement.

So I think they have accounted for it to take a reference to a array resource, as is in this case. 

I propose to leave it as is.

2023-10-19 18:19 UTC, tpdownes approved these changes
I was not entirely sure how to read

>If the reference is to a resource with multiple instances, a plan to update or replace any instance will trigger replacement.

but reading it again, it does feel like yours is the correct interpretation.

2023-10-23 16:54 UTC, nick-stroud commented
Spot check test failed in way that makes it seem that standard no placement policy case does not work, although this was tested manually. 

I am dismissing approval so this doesn't get merged until I have a chance to debug.

2023-11-17 00:10 UTC, nick-stroud commented
While it looks like `replace_triggered_by` can handle an array of instances, it does not seem to handle the case when count=0. I have updated to rely on a null_resource as a proxy for a trigger. I am dubious of this methodology but wanted to put something forward that is at least working as expected.

2023-11-17 17:47 UTC, tpdownes approved these changes
I see what you are doing here. I think the most direct route would be this:

1. Create a random suffix and have its lifecycle managed via the same null_resource you've created.
2. Apply that random suffix to the name of the resource policy
3. Remove the lifecycle from the VM

You can consider this at nit level but I think the basic problem is that the self_link of the resource policy isn't changing and you probably should change it if you're changing its properties.

2023-11-17 20:39 UTC, nick-stroud commented
I cannot get rid of the lifecycle on the VM. I get the following error:
```
Error: Error adding resource policies: googleapi: Error 400: Invalid resource usage: 'Instance must be in stopped state'., invalidResourceUsage
```

It looks like it still tries to modify the resource policy on the live VM instead of destroying the VM.

2023-11-17 20:50 UTC, merged