Adding snippet of commonly used images to make it easy to modify a blueprint
GoogleCloudPlatform/hpc-toolkit pull request #2014
Opened 2023-12-01 22:53 UTC by nick-stroud

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2023-12-04 17:48 UTC, cdunbar13 requested changes
LGTM other than this one line

2023-12-04 17:48 UTC, cdunbar13 commented on docs/vm-images.md
> +The following is a list of commonly used base images that can be used in a blueprint:
This line goes past 80 chars right?

2023-12-05 00:43 UTC, nick-stroud commented on docs/vm-images.md
> +The following is a list of commonly used base images that can be used in a blueprint:
Done.

2023-12-05 14:39 UTC, cdunbar13 approved these changes

2023-12-05 14:39 UTC, merged