Remove Slurm V4 modules and add note to use and reference V4 modules and
GoogleCloudPlatform/hpc-toolkit pull request #2160
Opened 2024-01-24 06:11 UTC by harshthakkar01

examples

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-01-25 19:43 UTC, harshthakkar01 commented
/gcbrun

2024-01-25 19:45 UTC, harshthakkar01 commented
Sending out for early review. 

TODO: Submit this after nfs-sql bp is updated to V6.

2024-01-25 21:12 UTC, mr0re1 approved these changes

2024-01-26 19:16 UTC, nick-stroud requested changes

2024-01-26 19:16 UTC, nick-stroud commented on modules/README.md
I am assuming that you did a repo wide search for module names (ex. `schedmd-slurm-on-gcp-controller`). Maybe also a search for `v4`.

2024-01-29 18:39 UTC, harshthakkar01 commented on README.md
> +> **_NOTE:_** Slurm V4 is deprecated. In case, you want to use V4 modules, please use
Done.

2024-01-29 18:40 UTC, harshthakkar01 commented on modules/README.md
> +[schedmd-slurm-on-gcp-login-node]: ../community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
Done.

2024-01-29 18:40 UTC, harshthakkar01 commented on modules/README.md
> -* **[SchedMD-slurm-on-gcp-partition]** ![community-badge] ![deprecated-badge] : Creates a partition
Done.

2024-01-29 19:18 UTC, harshthakkar01 commented on modules/README.md
Yes, thanks for the input. I found 1 extra link as well using v4 search. Updated that.

2024-01-30 03:29 UTC, nick-stroud commented on modules/README.md
What is the disposition on the failing tests?

2024-01-30 03:29 UTC, nick-stroud approved these changes

2024-01-30 06:22 UTC, harshthakkar01 commented on modules/README.md
* v6-tpu --> TPU not available.
* v5-ubuntu2004 --> known issue. fix is in progress.
* test-chrome-desktop --> wait for startup failing (not using slurm modules)
* hpc-slurm-chrome-desktop --> v5 module. not sure why it is failing. re-triggered.

2024-01-30 17:42 UTC, harshthakkar01 commented on modules/README.md
Offline discussion. These failures are not related to this PR.

2024-01-30 17:42 UTC, merged