Add v6 version of CAE blueprint
GoogleCloudPlatform/hpc-toolkit pull request #2325
Opened 2024-03-06 17:34 UTC by harshthakkar01

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-03-27 22:35 UTC, nick-stroud requested changes

2024-03-27 22:35 UTC, nick-stroud commented on examples/README.md
Update description.  
Also, since there is no integration test, what manual testing have you done (put in description).

2024-03-27 22:35 UTC, nick-stroud commented on examples/cae/README.md
Instructions still say "One or multiple Chrome Remote Desktop (CRD) sessions can be started dynamically through Slurm"

2024-03-30 03:27 UTC, harshthakkar01 commented on examples/cae/README.md
In the doc I added a note saying if customer wants to use v6 version, they can use different blueprint but the current documentation is for v5 version. That's why I didn't update the doc. 

Another alternative would be to add another documentation for v6. LMKWYT.

2024-04-01 23:03 UTC, harshthakkar01 commented on examples/README.md
Updated.

2024-04-01 23:04 UTC, harshthakkar01 commented on examples/README.md
Also, I will ping Felix offline for his opinion.

2024-04-03 02:57 UTC, nick-stroud approved these changes

2024-04-03 04:18 UTC, merged