Add slurm-gcp-high-io-v6 blueprint example and integration test
GoogleCloudPlatform/hpc-toolkit pull request #2330
Opened 2024-03-07 19:36 UTC by harshthakkar01

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-03-08 00:00 UTC, nick-stroud commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v6-high-io.yaml
What is this blueprint covering that slurm-enterprise does not have? I wonder if the existence of high io is just from timing since it pre-dated enterprise. I realize it would have been better to ask this in planning.

2024-03-08 23:30 UTC, harshthakkar01 commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v6-high-io.yaml
You are right. Nothing special. What do you propose ? Should we remove this and v5 as well ?

2024-03-09 01:20 UTC, nick-stroud commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v6-high-io.yaml
I agree with that course of action, so long as there is really no delta.

2024-03-12 05:31 UTC, harshthakkar01 commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v6-high-io.yaml
Updated to remove high-io-v5 example.

2024-03-12 18:21 UTC, nick-stroud requested changes

2024-03-12 18:21 UTC, nick-stroud commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v5-high-io.yaml
After reviewing high io and enterprise blueprints back to back, I believe the one thing we are loosing is that high io is the only blueprint that deploys a partition with multiple nodesets. 

Can we add multiple nodesets into another tested blueprint that we are keeping, one that is not in the examples folder, such as slurm-startup-script or lustre-slurm.

2024-03-12 21:00 UTC, harshthakkar01 commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v5-high-io.yaml
We have blueprint with 1 partition and multiple nodeset. For v6, it is 
tools/validate_configs/test_configs/node-groups-v6.yaml. 
#2347 

Will that be sufficient ?

2024-03-13 18:59 UTC, nick-stroud commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v5-high-io.yaml
Not if we don't deploy that blueprint. It provides some coverage as it will get run through ghpc create, but we will still be losing some coverage of deploying a blueprint with this configuration. I am hoping we can just tack this onto an existing test.

2024-03-14 16:54 UTC, harshthakkar01 commented on tools/cloud-build/daily-tests/blueprints/slurm-gcp-v5-high-io.yaml
Gotcha. There is a blueprint htc-slurm having multiple nodesets in single partition. I added test for v6 here
#2348

2024-03-15 22:08 UTC, nick-stroud approved these changes

2024-03-15 22:14 UTC, merged