Set default validation level to `ERROR`
GoogleCloudPlatform/hpc-toolkit pull request #2383
Opened 2024-03-20 04:24 UTC by mr0re1

**Motivation:** to safe new user from common deployment-time errors (e.g. APIs disabled)

2024-03-22 15:17 UTC, tpdownes requested changes
I would like a section at the top of

https://goo.gle/hpc-toolkit-troubleshooting

that links to

https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main?tab=readme-ov-file#gcp-credentials

Something like:

```yaml
## Troubleshooting

### Authentication

Confirm that you have [properly setup Google Cloud credentials](#gcp-credentials)

### Slurm Clusters
```

2024-03-22 15:18 UTC, tpdownes commented
For record, here is example output:

```
~/p/h/hpc-toolkit (elError)❯❯❯ ghpc deploy example-with-bad-project.yaml
validator "test_project_exists" failed:
Error: project ID bad-project-id does not exist or your credentials do not have permission to access it

One or more blueprint validators has failed. See messages above for suggested
actions. General troubleshooting guidance and instructions for configuring
validators are shown below.

- https://goo.gle/hpc-toolkit-troubleshooting
- https://goo.gle/hpc-toolkit-validation

Validators can be silenced or treated as warnings or errors:

- https://goo.gle/hpc-toolkit-validation-levels

validation failed due to the issues listed above
```

2024-03-22 21:45 UTC, mr0re1 commented
Thank you for suggestion. Done

2024-03-25 13:20 UTC, tpdownes approved these changes

2024-03-25 16:23 UTC, merged