Add example using Slurm static compute nodes
GoogleCloudPlatform/hpc-toolkit pull request #2393
Opened 2024-03-22 05:10 UTC by nick-stroud

Adds example and test that captures best practices found in the new static nodes cloud docs.

* [About [Slurm] node types](https://cloud.google.com/hpc-toolkit/docs/slurm/node-types)
* [Best practices for static compute nodes](http://cloud/hpc-toolkit/docs/slurm/static-nodes-best-practices)
* [Reconfigure a running cluster](http://cloud/hpc-toolkit/docs/slurm/reconfigure-cluster)
* [Manage static compute nodes](http://cloud/hpc-toolkit/docs/slurm/manage-static-nodes)

Integration test requires creating reservation prior to deployment.

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-03-22 15:00 UTC, tpdownes requested changes
The overall concept and blueprint looks good. There are 2 issues to think over and address:

1. The `make tests` failure for an undefined reservation name. You can look at the A3 blueprint for solutions, though I think we need to do better than that as a follow up task
2. Ensuring the reservation is deleted even when ghpc destroy fails. I suggest one approach, but there is probably some thought/discussion to be had.

2024-03-25 15:33 UTC, nick-stroud commented on examples/hpc-slurm-static-v6.yaml
> +  static_reservation_name:  ## Set your reservation name here ##
I have handled in a similar way. Agreed, area for further improvement in the future.

2024-03-25 15:34 UTC, nick-stroud commented on community/modules/scheduler/schedmd-slurm-gcp-v6-login/metadata.yaml
> +  # inject_module_id: name_prefix
removed.

2024-03-25 15:39 UTC, nick-stroud commented on tools/cloud-build/daily-tests/ansible_playbooks/tasks/rescue_ghpc_failure.yml
> +- name: Run post destroy tasks
Next I would like to add compact placement to the reservation (future PR), and compact placement does require that VMs are deleted before placement policy is deleted. I have added a block with always to make sure it aways runs. 

I have tested the nested always logic with the following test ansible files.

```
---
- name: Testing nested always
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Mock Test Block
    block:
    - name: Mock Test
      ansible.builtin.debug:
        msg: Mock Test
    - name: Trigger failure
      ansible.builtin.fail:
        msg: Test Fails
    always:
    - name: Import Cleanup
      ansible.builtin.include_tasks:
        file: block_testing_task.yml
        apply:
          delegate_to: localhost
```

```
# block_testing_task.yml
---
- name: Cleanup Block
  block:
  - name: Mock Destroy
    ansible.builtin.debug:
      msg: Mock Destroy
  - name: Destroy Fails
    ansible.builtin.fail:
      msg: Destroy Fails
  always:
  - name: Mock Post Destroy
    ansible.builtin.debug:
      msg: Mock Post Destroy
```

2024-03-25 15:40 UTC, nick-stroud commented on tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-reservation.yml
> +  ansible.builtin.command: gcloud compute reservations delete {{ custom_vars.reservation_name }} --project={{ project }}  --zone={{ zone }} --quiet
Ack.

2024-03-25 18:51 UTC, tpdownes approved these changes

2024-03-25 19:30 UTC, merged