Release v1.31.0
GoogleCloudPlatform/hpc-toolkit pull request #2394
Opened 2024-03-22 17:31 UTC by rohitramu

2024-03-27 20:57 UTC, nick-stroud approved these changes

2024-03-27 21:03 UTC, harshthakkar01 approved these changes

2024-03-27 23:09 UTC, cboneti requested changes
Could we discuss updating https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/machine-learning/README.md ?

2024-03-28 18:51 UTC, nick-stroud approved these changes

2024-03-28 18:51 UTC, nick-stroud commented
Discussion with @tpdownes, He is working on docs update as hotfix but does not want to hold release.

2024-03-28 19:01 UTC, harshthakkar01 commented
Good to go from my side. Only todo for this PR would be,

Update the Release title and description.

2024-03-28 19:01 UTC, harshthakkar01 approved these changes

2024-03-28 19:04 UTC, merged