Resolve Ansible crash in Spack installation
GoogleCloudPlatform/hpc-toolkit pull request #2462
Opened 2024-04-09 19:32 UTC by tpdownes

Do not follow symbolic links in recursive chmod. Should resolve observed problems with filenames that are so long:

```
    /sw/spack/lib/spack/docs/../../../lib/spack/docs/../../../...
```

> ### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-04-10 00:49 UTC, nick-stroud requested changes

2024-04-10 00:49 UTC, nick-stroud commented on community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
I don't see this as a risky change (_Previous to Ansible 2.5, this was false by default_) but I am concerned that we don't fully understand the issue. At the time that this Ansible step is running, all that has really happened is a clean copy of the Spack repo has been cloned. I don't see any odd linking in the spack repo under `spack/lib/spack/docs/`.

As this is targeted at fixing the AMD blueprint, I have asked @harshthakkar01 to rebase on this commit/PR and confirm the bug is resolved, prior to merging this PR. Essentially, block merging this PR until we can confirm in resolves the issue.

It may be that we have an obvious way of testing that this resolves the issue other than @harshthakkar01 testing. Forgive me if I am just out of the loop.

2024-04-10 00:50 UTC, nick-stroud commented
@harshthakkar01 please reassign to me for approval once you have confirmed with your testing.

2024-04-11 19:29 UTC, harshthakkar01 commented on community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
Tested this PR with #2411 . Added the manual testing results in the canonical bug. This manual testing involes the steps mentioned in the AMD doc. https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main/community/examples/AMD#amd-solutions-for-the-hpc-toolkit

2024-04-11 19:30 UTC, harshthakkar01 approved these changes

2024-04-12 05:18 UTC, nick-stroud approved these changes

2024-04-12 16:56 UTC, merged