Update Intel DAOS community examples to use google-cloud-daos v0.2.1
GoogleCloudPlatform/hpc-toolkit pull request #427
Opened 2022-07-19 01:45 UTC by markaolson

DAOS v2.0.3 was released and as a result a few minor changes were made in
the https://github.com/daos-stack/google-cloud-daos repository.

This change updates the examples in community/examples/intel to use
to use the terraform modules from
https://github.com/daos-stack/google-cloud-daos/releases/tag/v0.2.1

Signed-off-by: Mark A. Olson <mark.a.olson@intel.com>

2022-07-19 17:25 UTC, tpdownes commented
@markaolson thank you for the submission. We will review it promptly.

2022-07-19 19:37 UTC, tpdownes requested changes
I have confirmed that `community/examples/intel/daos-cluster.yaml` can be provisioned but have not verified functionality beyond that (I am OK with that).

Please make the following minor changes

- state a minimum DAOS release in the commit message
- update `community/modules/file-system/Intel-DAOS/README.md` with a minimum DAOS release and/or tag on @daos-stack/google-cloud-daos from which to build images

I started from the latest commit on the google-cloud-daos repo and want to know if our users **need** to do so as well.

2022-07-19 22:21 UTC, tpdownes commented
Alternatively, write the DAOS version requirements here and I can make the changes I'd like to see.

2022-07-20 00:46 UTC, markaolson commented
I added a section in `community/modules/file-system/Intel-DAOS/README.md` that explains the need to ensure that the DAOS server image is built with the same tagged version of the https://github.com/daos-stack/google-cloud-daos repository that is referenced for the daos_server module in the blueprint.  

That's really the best way to ensure that the DAOS server image has what the specific version of the daos_server terraform module is expecting.

There will be times when you could use an older DAOS server image with a newer version of the daos_server terraform module without any issues.  However, that won't always be the case.  So it's best to always build your DAOS server image from the same tagged version of the repo that the modules use in the HPC Toolkit blueprints.

2022-07-20 17:05 UTC, tpdownes approved these changes
LGTM. Thanks for adding the clarification that works now and going forward.

2022-07-20 17:05 UTC, tpdownes commented
/gcbrun

2022-07-20 17:24 UTC, merged