Additional validation for blueprint_name
GoogleCloudPlatform/hpc-toolkit pull request #482
Opened 2022-08-16 20:31 UTC by kkr16

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [x] Have you written unit tests to cover this change?
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

### Changes
Proposing a change to validate `blueprint_name` against label value naming constraints as defined in the Google Cloud [docs](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).

2022-08-17 00:47 UTC, cboneti commented on pkg/config/config.go
> +	err = dc.Config.checkBlueprintName()
I feel that everything that will eventually become a label (blueprint name, deployment name, etc) should run this test. Should you not generalize to check label requirements? and then run it for both blueprint name and deployment name?

2022-08-17 00:49 UTC, cboneti commented
/gcbrun

2022-08-17 23:25 UTC, heyealex requested changes

2022-08-17 23:25 UTC, heyealex commented on pkg/config/config.go
> +func (b *Blueprint) checkBlueprintName() error {
Based on what Carlos suggested, I'd change this function to `checkLabelValue` with the same validation. With that, you could run the same test against deployment_name in the Config.DeploymentName() function as well.

This also helps generalize as we add features. There may be other labels that we track and having the function ready to go will be very valuable.

2022-08-17 23:25 UTC, heyealex commented on pkg/config/config_test.go
> +	// Does deployment_name contain special characters other than dashes or underscores?
A couple more tests you could include:
* Test with an underscore (succeed)
* Test with a capital letter (fail)

2022-08-22 21:25 UTC, heyealex commented
/gcbrun

2022-08-22 22:13 UTC, heyealex commented
/gcbrun

2022-08-22 23:15 UTC, heyealex commented
/gcbrun

2022-08-22 23:19 UTC, cboneti approved these changes

2022-08-22 23:22 UTC, merged