remove "kind:" from examples and docs where optional
GoogleCloudPlatform/hpc-toolkit pull request #547
Opened 2022-09-13 22:12 UTC by kkr16

### Description

- updated [examples/README.md](https://github.com/GoogleCloudPlatform/hpc-toolkit/compare/develop...kkr16:develop?expand=1#diff-49aaa2819e35a856818ecec8c9fa7e1c79ad028d3f44bd749736353cfb51bac9) to state that `kind` is optional and default is `terraform`
- removed `kind: terraform` from docs and examples 

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [x] Have you written unit tests to cover this change? 
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

2022-09-14 00:34 UTC, cboneti commented
/gcbrun

2022-09-14 15:59 UTC, heyealex requested changes
Thank you for the PR submission! This change touched a lot of files, and I appreciate your attention to detail. 

I just have the one comment I'd like to have addressed, and that should just be a `git restore` on a one or two of the test_configs to ensure the optional variable is still being validated in `make tests`.

2022-09-16 03:07 UTC, kkr16 commented on tools/validate_configs/test_configs/2-nfs-servers.yaml
> -    kind: terraform
I restored two tests to include `kind: terraform`
- `tools/validate_configs/test_configs/packer.yaml`
- `tools/validate_configs/test_configs/threads_per_core.yaml`

2022-09-16 03:14 UTC, kkr16 commented
> Thank you for the PR submission! This change touched a lot of files, and I appreciate your attention to detail.
> 
> I just have the one comment I'd like to have addressed, and that should just be a `git restore` on a one or two of the test_configs to ensure the optional variable is still being validated in `make tests`.

Thank you for the feedback! 
Comment addressed. ptal.

2022-09-16 16:06 UTC, heyealex commented
/gcbrun

2022-09-16 16:12 UTC, heyealex commented
/gcbrun

2022-09-16 16:14 UTC, heyealex approved these changes
Thanks for the update, this looks good!

2022-09-16 16:19 UTC, merged