Update Intel DAOS community examples to use google-cloud-daos v0.3.0
GoogleCloudPlatform/hpc-toolkit pull request #784
Opened 2022-12-13 00:18 UTC by mark-olson

The DAOS Terraform modules in the daos-stack/google-cloud-daos repository were updated to work with DAOS v2.2.0. The updates were tagged v0.3.0.

As a result the community/examples/intel/daos-*.yaml blueprints were updated to use the v0.3.0 terraform modules in the daos-stack/google-cloud-daos repository.

Signed-off-by: Mark Olson <115657904+mark-olson@users.noreply.github.com>

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [ ] Are all tests passing? (`make tests`)
* [ ] Have you written unit tests to cover this change?
* [ ] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

2022-12-13 00:36 UTC, cboneti commented
/gcbrun

2022-12-27 19:16 UTC, tpdownes commented
/gcbrun

2022-12-27 19:34 UTC, tpdownes requested changes
@mark-olson 

As always, thanks for the commit and for resolving your CLA signature a couple weeks ago. I have relatively minor concerns.

1. Revert accidental modification of the TOC for the Intel README.
2. Address probably minor questions.

I have not yet tested the solution, but that might be best for @cboneti who will return from travel before I do.

2022-12-27 19:34 UTC, tpdownes commented on community/examples/intel/README.md
> +- [Intel-Optimized Slurm Cluster](#intel-optimized-slurm-cluster)
@mark-olson I believe that you accidentally removed the top-level TOC item here.

When I run

```
md_toc github -l 4 community/examples/intel/README.md
```

I see that there are no changes from the develop branch. I propose the following:

1. You revert the changes to the TOC
2. You or I update the comment on line 3 to include the command I show above. If you do it, please include it in this PR. If you would rather I do it, a Toolkit team member will submit a separate PR.

2022-12-27 19:34 UTC, tpdownes commented on community/examples/intel/README.md
> +  --properties rf:0
Is this intentional? I don't see a mention in commit and I lack the relevant expertise.

2022-12-27 19:34 UTC, tpdownes commented on community/examples/intel/README.md
> +popd
Is this intentional? I don't see a mention in commit and I lack the relevant expertise.

2022-12-27 19:35 UTC, tpdownes commented on community/examples/intel/README.md
> +- [Intel-Optimized Slurm Cluster](#intel-optimized-slurm-cluster)
If you lack easy access to https://pypi.org/project/md-toc/ in your working environment, please let me know.

2023-01-12 19:17 UTC, mark-olson commented
This PR is outdated and had some issues.  Closing it. I will submit a new one.

2023-01-12 19:17 UTC, closed without merging