Pin terraform google provider to v4.53
GoogleCloudPlatform/hpc-toolkit pull request #929
Opened 2023-02-16 21:52 UTC by nick-stroud

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [x] Have you written unit tests to cover this change?
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

2023-02-16 21:59 UTC, tpdownes approved these changes

2023-02-16 21:59 UTC, tpdownes requested changes
Actually, please pin to 4.53.1 (and above, just replace the 0 with a 1). There is a known problem with 4.53.0

2023-02-16 23:54 UTC, tpdownes approved these changes

2023-02-17 17:29 UTC, nick-stroud commented
Group 5 passed on the previous commit (before force push) so I am not concerned to rerun.

2023-02-17 17:29 UTC, merged